version: '3'
services:
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=user_db
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"